#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Sep 20 13:48:17 2017

@author: fmjgreenstreet
"""

# import the necessary packages
from collections import deque
import numpy as np
import cv2
import math
import imutils 


def colourObjFindr(colourLower, colourUpper):
    mask = cv2.inRange(hsv, colourLower, colourUpper)
    mask = cv2.erode(mask, None, iterations=2)
    mask = cv2.dilate(mask, None, iterations=2)
    

	# find contours in the mask and initialize the current
	# (x, y) center of the ball
    cnts = cv2.findContours(mask.copy(), cv2.RETR_EXTERNAL,
		cv2.CHAIN_APPROX_SIMPLE)[-2]
    center = None

	# only proceed if at least one contour was found
    if len(cnts) > 0:
		# find the largest contour in the mask, then use
		# it to compute the minimum enclosing circle and
		# centroid
        print ('found an object')
        c = max(cnts, key=cv2.contourArea)
        ((x, y), radius) = cv2.minEnclosingCircle(c)
        M = cv2.moments(c)
        center = (int(M["m10"] / M["m00"]), int(M["m01"] / M["m00"]))
        
        if radius > 1:
            cv2.circle(frame, (int(x), int(y)), int(radius),
				(0, 255, 255), 2)
            cv2.circle(frame, center, 5, (255, 255, 255), -1)
            
    return center

# define the lower and upper boundaries of the "red"
# ball in the HSV color space, then initialize the
# list of tracked points
greenLower = (29, 10, 10)
greenUpper = (64, 255, 255)
redLower = (18,63,0)
redUpper = (44,169,255)
blueLower = (91, 70, 49)
blueUpper = (136, 255, 255)
whiteLower = (0, 0, 240)
whiteUpper = (255, 255, 255)

camera = cv2.VideoCapture(1)


# keep looping
while True:
    # grab the current frame
    (grabbed, frame) = camera.read()
    frame = imutils.resize(frame, width=600)

    # blur it, and convert it to the HSV
	# color space
    hsv = cv2.cvtColor(frame, cv2.COLOR_BGR2HSV)
    
    Rcenter = colourObjFindr(redLower, redUpper)
    Gcenter = colourObjFindr(greenLower, greenUpper)
    Bcenter = colourObjFindr(blueLower, blueUpper)
    Wcenter = colourObjFindr(whiteLower, whiteUpper)

            
	# show the frame to our screen
    cv2.imshow("Frame", frame)
    key = cv2.waitKey(1) & 0xFF

	# if the 'q' key is pressed, stop the loop
    if key == ord("q"):
        break
        cv2.destroyAllWindows()

# cleanup the camera and close any open windows
camera.release()
cv2.destroyAllWindows()
